Refactoring story builder
infoshareacademy/jcszr7-OstreC pull request #63
Opened 2023-03-25 14:03 UTC by michal-tracichleb

Small changes

2023-03-25 17:14 UTC, sebastianCz commented on OstreCWEB/OstreCWEB.Data/Configurations/ParagraphItemConfiguration.cs
Dlaczego usunelismy klucz kompozytowy?

2023-03-25 17:26 UTC, sebastianCz requested changes
Just one class + 1 comment to change, sry but it will be a disaster if you merge it with something.

2023-03-25 17:26 UTC, sebastianCz commented on OstreCWEB/OstreCWEB.Data/Migrations/OstreCWebContextModelSnapshot.cs
Sprawdzales czy ten klucz nie wysypuje momentu dodawania itemow do postaci w grze?

2023-03-25 17:26 UTC, sebastianCz commented on OstreCWEB/OstreCWEB/ViewModel/Game/StartGameView.cs
No, it won't be merged. Remove that comment, I'm working on it.

2023-03-25 18:34 UTC, michal-tracichleb commented on OstreCWEB/OstreCWEB.Data/Configurations/ParagraphItemConfiguration.cs
Aby była możliwość usunięcia po id itemu z paragrapfu oraz żeby nie było problemy z większą ilością itemów dodawanych do paragrapfu

2023-03-25 18:35 UTC, michal-tracichleb commented on OstreCWEB/OstreCWEB.Data/Migrations/OstreCWebContextModelSnapshot.cs
To jest paragraph item, nie character item

2023-03-26 08:10 UTC, sebastianCz commented
as discussed -> ok to merge.

2023-03-26 08:11 UTC, sebastianCz approved these changes

2023-03-26 09:11 UTC, merged